# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField(default=1)),
                ('particles', models.CharField(choices=[('bs', 'Bosons'), ('fr', 'Fermions')], max_length=2)),
                ('gs_ft', models.CharField(choices=[('gs', 'GS'), ('ft', 'FT')], max_length=2)),
                ('trap', models.BooleanField()),
                ('spin_imbalance', models.BooleanField()),
                ('mass_imbalance', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
            ],
        ),
    ]
