# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField(default=1)),
                ('particles', models.CharField(choices=[('bs', 'Bosons'), ('fr', 'Fermions')], max_length=2)),
                ('gs_ft', models.CharField(choices=[('gs', 'GS'), ('ft', 'FT')], max_length=2)),
                ('trap', models.BooleanField()),
                ('spin_imbalance', models.BooleanField()),
                ('mass_imbalance', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('link', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArxivXML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('authors', models.CharField(max_length=1000)),
                ('abstract', models.TextField()),
                ('arxiv_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserArxivXML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curated', models.BooleanField(default=False)),
                ('arxiv_xml', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.ArxivXML')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arxivxml',
            name='users',
            field=models.ManyToManyField(through='search.UserArxivXML', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='user_arxiv_xml',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.UserArxivXML'),
        ),
    ]
