# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
