# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_article_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArxivXML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('arxiv_id', models.CharField(max_length=200)),
            ],
        ),
    ]
